/**
 * Regression tests for Drilldown Fields caching behavior.
 *
 * Guards against:
 *   - query_range TTL-as-step bug: using step (up to 1h) as cache TTL caused
 *     visible right-edge gaps in field charts (empty area from cached-data-end to now)
 *   - labels not loading for wide time ranges (labels regression)
 *   - inconsistent behavior across time ranges (some load, some don't)
 *
 * Coverage: 30m, 1h, 2h, 6h, 12h, 2d, 7d time ranges.
 */
import { test, expect, type Page } from "@playwright/test";
import {
  PROXY_INTERACT_DS,
  installGrafanaGuards,
  resolveDatasourceUid,
  waitForGrafanaReady,
  drilldownLabelFilter, drilldownFieldFilter,
} from "./helpers";
import { buildServiceDrilldownUrl } from "./url-state";

// Use a service that has consistent log generation in the e2e stack.
// frontend-ssr and api-gateway are both generated by log-generator.py.
const TEST_SERVICE = "api-gateway";

const TIME_RANGES = [
  { from: "now-30m", to: "now", label: "30m" },
  { from: "now-1h",  to: "now", label: "1h"  },
  { from: "now-2h",  to: "now", label: "2h"  },
  { from: "now-6h",  to: "now", label: "6h"  },
  { from: "now-12h", to: "now", label: "12h" },
  { from: "now-2d",  to: "now", label: "2d"  },
  { from: "now-7d",  to: "now", label: "7d"  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

async function openFieldsView(
  page: Page,
  datasource: string,
  serviceName: string,
  from: string,
  to: string
): Promise<void> {
  const uid = await resolveDatasourceUid(page, datasource);
  const url = buildServiceDrilldownUrl(uid, serviceName, "fields", { from, to });
  await page.goto(url);
  await waitForGrafanaReady(page);
  // Fields tab is ready when "Filter by fields" combobox appears
  await expect(
    drilldownFieldFilter(page)
  ).toBeVisible({ timeout: 45_000 });
}

// ─────────────────────────────────────────────────────────────────────────────
// Test group 1: fields tab loads without HTTP/UI errors for each time range
// ─────────────────────────────────────────────────────────────────────────────

test.describe("Drilldown Fields — all time ranges load without errors @drilldown-cache", () => {
  for (const { from, to, label } of TIME_RANGES) {
    test(`no errors — ${label} range`, async ({ page }) => {
      // Wide ranges (7d) load more logfmt queries via the direct stats path and
      // need extra time for VL to parse and aggregate the full window.
      if (label === "7d") test.setTimeout(120_000);

      const guards = installGrafanaGuards(page, {
        allowedAlertErrors: [/^Unknown error$/i],
        allowedResponseErrors: [
          // Patterns endpoint returns 400/empty when no patterns exist — not a proxy defect
          /\/loki\/api\/v1\/patterns/,
          // Grafana's api/ds/query returns 400 when VL rejects a translated query
          // (e.g. label!=value filters that VL renders as _stream:!"" which it rejects).
          // These failures are a known VL gap, not a regression in caching or proxy routing.
          /\/api\/ds\/query/,
        ],
      });

      await openFieldsView(page, PROXY_INTERACT_DS, TEST_SERVICE, from, to);
      // Give charts 2 seconds to render before checking for errors
      await page.waitForTimeout(2_000);
      await guards.assertClean();
    });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// Test group 2: labels sidebar is populated for each time range
// (regression guard for the "labels not loading" issue on wide ranges)
// ─────────────────────────────────────────────────────────────────────────────

test.describe("Drilldown Fields — labels sidebar is populated @drilldown-cache @drilldown-core", () => {
  for (const { from, to, label } of TIME_RANGES) {
    test(`labels visible — ${label} range`, async ({ page }) => {
      await openFieldsView(page, PROXY_INTERACT_DS, TEST_SERVICE, from, to);

      const filterByLabels = drilldownLabelFilter(page);
      await expect(filterByLabels).toBeVisible({ timeout: 30_000 });

      // Options load asynchronously after opening the dropdown. Require a
      // visible result; the loading state does not establish an empty response.
      await filterByLabels.click();
      const options = page.getByRole("option");
      await expect(options.first(), `labels dropdown is empty for ${label} range`)
        .toBeVisible({ timeout: 30_000 });

      await page.keyboard.press("Escape");
    });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// Test group 3: no right-edge gap in field charts
//
// Regression guard for: using step (up to 1h) as the query_range cache TTL.
// With TTL=step=1h, VL is only queried once per hour. By the time the cache
// was populated 55min ago, the chart "end" is now+55min relative to the data —
// producing a visible 55-min empty strip at the right edge of every field chart.
//
// Fix: TTL=5min so cached data is never more than 5 min stale.
//
// Test strategy: intercept query_range responses, collect the last data-point
// timestamp for each field chart query (step ≥ 1800s), and assert that the
// maximum gap between the last point and the request's "end" does not exceed
// 3 × step (lenient enough to survive bucketing and a cold cache, tight enough
// to catch the 1-hour regression).
// ─────────────────────────────────────────────────────────────────────────────

test.describe("Drilldown Fields — no right-edge gap in charts @drilldown-cache", () => {
  for (const { from, to, label } of TIME_RANGES) {
    test(`chart data covers end of window — ${label} range`, async ({ page }) => {
      // max seconds from end-of-window to last data point that we'll accept
      // = 3 × step. For step=3600s this is 3h, which is generous but still
      // catches a regression where the gap equals the full TTL (≤ 1h here) plus
      // one step. Reduce to 2×step once the e2e stack has denser data.
      const MAX_GAP_STEPS = 3;

      // { step: maxObservedGapSeconds }
      const gapsByStep = new Map<number, number>();
      // { step: endSeconds } — track the latest end param seen per step
      const endByStep = new Map<number, number>();

      await page.route("**loki/api/v1/query_range**", async (route) => {
        const reqUrl = new URL(route.request().url());
        const endSec = parseFloat(reqUrl.searchParams.get("end") ?? "0");
        const stepSec = parseFloat(reqUrl.searchParams.get("step") ?? "0");

        // Only track field-chart-shaped queries: step ≥ 30s (metric range)
        // and the query contains count_over_time (Drilldown field histogram shape)
        const query = reqUrl.searchParams.get("query") ?? "";
        const isFieldChart = stepSec >= 30 && query.includes("count_over_time");

        const response = await route.fetch();

        if (isFieldChart && endSec > 0) {
          try {
            const body = await response.json() as {
              data?: { result?: Array<{ values?: Array<[number, string]> }> };
            };
            let lastTs = 0;
            for (const series of body?.data?.result ?? []) {
              const vals = series?.values ?? [];
              if (vals.length > 0) {
                const ts = Number(vals[vals.length - 1][0]);
                if (ts > lastTs) lastTs = ts;
              }
            }
            if (lastTs > 0) {
              const gapSec = endSec - lastTs;
              const prev = gapsByStep.get(stepSec) ?? 0;
              if (gapSec > prev) gapsByStep.set(stepSec, gapSec);
            }
            const prevEnd = endByStep.get(stepSec) ?? 0;
            if (endSec > prevEnd) endByStep.set(stepSec, endSec);
          } catch {
            // ignore JSON parse errors
          }
          await route.fulfill({ response });
        } else {
          await route.continue();
        }
      });

      await openFieldsView(page, PROXY_INTERACT_DS, TEST_SERVICE, from, to);
      // Let all field chart requests settle
      await page.waitForTimeout(4_000);

      for (const [stepSec, maxGapSec] of gapsByStep) {
        const allowedGap = MAX_GAP_STEPS * stepSec;
        expect(
          maxGapSec,
          `field chart right-edge gap for step=${stepSec}s on ${label} range: ` +
          `${maxGapSec}s (allowed: ${allowedGap}s = ${MAX_GAP_STEPS}×step). ` +
          `Likely cause: query_range TTL > step (TTL-as-step regression).`
        ).toBeLessThanOrEqual(allowedGap);
      }
    });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// Test group 4: second load is served from compat cache (timing guard)
//
// After the first load populates the compat cache, a second load within the
// same 5-min bucket should be faster because query_range responses come from
// the proxy's in-memory cache instead of VL.
//
// This is a timing-based heuristic: we flag a regression if the second load
// is materially SLOWER than the first (which would indicate cache misses).
// ─────────────────────────────────────────────────────────────────────────────

test.describe("Drilldown Fields — repeated loads served from cache @drilldown-cache", () => {
  // Only test the two widest ranges where caching has the most impact (step is largest)
  for (const { from, to, label } of TIME_RANGES.filter((r) =>
    ["2d", "7d"].includes(r.label)
  )) {
    test(`second load not slower than first — ${label} range`, async ({ page }) => {
      const totalMs: number[] = [];

      await page.route("**loki/api/v1/query_range**", async (route) => {
        const t0 = Date.now();
        const response = await route.fetch();
        totalMs.push(Date.now() - t0);
        await route.fulfill({ response });
      });

      // First load — populates compat cache
      await openFieldsView(page, PROXY_INTERACT_DS, TEST_SERVICE, from, to);
      await page.waitForTimeout(2_000);

      const firstLoad = totalMs.splice(0);

      // Second load — should hit compat cache
      await page.reload();
      await waitForGrafanaReady(page);
      await expect(
        drilldownFieldFilter(page)
      ).toBeVisible({ timeout: 45_000 });
      await page.waitForTimeout(2_000);

      const secondLoad = [...totalMs];

      if (firstLoad.length === 0 || secondLoad.length === 0) {
        // No query_range calls intercepted — skip assertion
        return;
      }

      const avgFirst = firstLoad.reduce((a, b) => a + b, 0) / firstLoad.length;
      const avgSecond = secondLoad.reduce((a, b) => a + b, 0) / secondLoad.length;

      // Second load must not be more than 2× slower than the first.
      // Cache hits are typically < 50ms; VL calls are 200ms–2s.
      // A factor of 2 allows for timing variance while still catching
      // a total cache miss on the second load.
      expect(
        avgSecond,
        `second load (${avgSecond.toFixed(0)}ms avg over ${secondLoad.length} reqs) ` +
        `should not be >2× slower than first (${avgFirst.toFixed(0)}ms avg) — ` +
        `may indicate cache misses on repeated loads for ${label} range`
      ).toBeLessThanOrEqual(avgFirst * 2);
    });
  }
});
