package proxy

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"
)

func TestExtractCommonBase(t *testing.T) {
	tests := []struct {
		query     string
		wantBase  string
		wantField string
		wantOK    bool
	}{
		{
			query:     `{app="foo"} | filter trace_id != ""`,
			wantBase:  `{app="foo"}`,
			wantField: "trace_id",
			wantOK:    true,
		},
		{
			query:     `{app="foo"} | json | filter trace_id != ""`,
			wantBase:  `{app="foo"}`,
			wantField: "trace_id",
			wantOK:    true,
		},
		{
			query:     `{app="foo"} | unpack_json | filter span_id != ""`,
			wantBase:  `{app="foo"}`,
			wantField: "span_id",
			wantOK:    true,
		},
		{
			query:     `{app="foo"} | logfmt | filter level != ""`,
			wantBase:  `{app="foo"}`,
			wantField: "level",
			wantOK:    true,
		},
		{
			// VL translated format: field:!"" (generated by translator from field!="")
			query:     `{app="foo"} | unpack_json | filter trace_id:!""`,
			wantBase:  `{app="foo"}`,
			wantField: "trace_id",
			wantOK:    true,
		},
		{
			// Quoted dotted field — translator quotes OTel attributes like k8s.pod.name
			// because VL requires quoting for identifiers with dots.
			query:     `{app="foo"} | unpack_json | filter "k8s.pod.name":!""`,
			wantBase:  `{app="foo"}`,
			wantField: "k8s.pod.name",
			wantOK:    true,
		},
		{
			query:     `{app="foo"} | unpack_json | filter "service.name":!""`,
			wantBase:  `{app="foo"}`,
			wantField: "service.name",
			wantOK:    true,
		},
		{
			query:  `{app="foo"}`,
			wantOK: false,
		},
		{
			query:  `{app="foo"} | stats by (level) count() as c`,
			wantOK: false,
		},
	}
	for _, tc := range tests {
		t.Run(tc.query, func(t *testing.T) {
			base, field, ok := extractCommonBase(tc.query)
			if ok != tc.wantOK {
				t.Fatalf("ok=%v want %v", ok, tc.wantOK)
			}
			if !ok {
				return
			}
			if base != tc.wantBase {
				t.Errorf("base=%q want %q", base, tc.wantBase)
			}
			if field != tc.wantField {
				t.Errorf("field=%q want %q", field, tc.wantField)
			}
		})
	}
}

func TestExtractStreamSelectorOnly(t *testing.T) {
	tests := []struct {
		query string
		want  string
	}{
		// Loki-bracketed form: trims at first pipe
		{`{namespace="prod"}`, `{namespace="prod"}`},
		{`{namespace="prod"} | json`, `{namespace="prod"}`},
		{`{namespace="prod"} | json | logfmt | drop a,b`, `{namespace="prod"}`},
		// VL-native bare form: still trims at first pipe
		{`namespace:="prod"`, `namespace:="prod"`},
		{`namespace:="prod" | unpack_json`, `namespace:="prod"`},
		{`namespace:="prod" | unpack_json | filter trace_id:!""`, `namespace:="prod"`},
		// Multi-label selectors preserved intact
		{`{namespace="prod", app="api"} | json`, `{namespace="prod", app="api"}`},
		// Whitespace handling
		{`  {namespace="prod"}  |  json  `, `{namespace="prod"}`},
		{``, ``},
	}
	for _, tc := range tests {
		t.Run(tc.query, func(t *testing.T) {
			got := extractStreamSelectorOnly(tc.query)
			if got != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

func TestFieldHasExistenceFilter_QuotedDottedField(t *testing.T) {
	// Regression: the translator quotes OTel attributes ("k8s.pod.name",
	// "service.name") because VL requires quoting for identifiers with dots.
	// Pre-fix, fieldHasExistenceFilter only checked the unquoted form, causing
	// the parser-direct fast path (and /hits routing) to be skipped for these
	// fields — Drilldown rendered 100k+ raw series instead of the top-N
	// histogram. See proxyStatsQueryRangeDrilldownParserDirect.
	tests := []struct {
		base  string
		field string
		want  bool
	}{
		{`namespace:="prod" | unpack_json | filter "k8s.pod.name":!""`, "k8s.pod.name", true},
		{`namespace:="prod" | unpack_json | filter "service.name":!""`, "service.name", true},
		{`namespace:="prod" | unpack_json | filter trace_id:!""`, "trace_id", true},
		// Quoted field present but different from requested
		{`namespace:="prod" | unpack_json | filter "k8s.pod.name":!""`, "trace_id", false},
		// Stream-selector form (already worked, regression guard)
		{`{namespace="prod", trace_id!=""}`, "trace_id", true},
	}
	for _, tc := range tests {
		t.Run(tc.field, func(t *testing.T) {
			if got := fieldHasExistenceFilter(tc.base, tc.field); got != tc.want {
				t.Errorf("got %v, want %v\n  base:  %s\n  field: %s", got, tc.want, tc.base, tc.field)
			}
		})
	}
}

func TestAllFiltersAreExistenceChecks(t *testing.T) {
	tests := []struct {
		name  string
		query string
		want  bool
	}{
		// Loki format (field != "")
		{`loki-single`, `{app="foo"} | filter trace_id != ""`, true},
		{`loki-multi`, `{app="foo"} | filter trace_id != "" | filter span_id != ""`, true},
		{`loki-value-comparison`, `{app="foo"} | filter status != ""`, true},
		{`loki-non-existence`, `{app="foo"} | filter status >= 400`, false},
		// VL translated format (field:!"") — what the translator generates from field!=""
		{`vl-single`, `env:="production" | unpack_json | delete __error__ | filter trace_id:!""`, true},
		{`vl-multi`, `env:="production" | delete __error__ | filter span_id:!"" | filter trace_id:!""`, true},
		{`vl-with-value-comparison`, `env:="production" | filter trace_id:!"" | filter status:>="400"`, false},
		{`vl-no-filter`, `env:="production" | delete __error__`, true},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := allFiltersAreExistenceChecks(tc.query)
			if got != tc.want {
				t.Errorf("allFiltersAreExistenceChecks(%q) = %v, want %v", tc.query, got, tc.want)
			}
		})
	}
}

func TestDetectDrilldownSingleField(t *testing.T) {
	tests := []struct {
		name      string
		query     string
		wantOK    bool
		wantBase  string
		wantField string
	}{
		{
			name:      "clean drilldown query after strip",
			query:     `env:="production" | filter trace_id:!"" | stats by (trace_id) count()`,
			wantOK:    true,
			wantBase:  `env:="production"`,
			wantField: "trace_id",
		},
		{
			name:      "multiple stream filters, single existence filter",
			query:     `env:="production" app:="myapp" | filter span_id:!"" | stats by (span_id) count()`,
			wantOK:    true,
			wantBase:  `env:="production" app:="myapp"`,
			wantField: "span_id",
		},
		{
			name:      "delete pipe stripped",
			query:     `env:="production" | delete __error__ | filter trace_id:!"" | stats by (trace_id) count()`,
			wantOK:    true,
			wantBase:  `env:="production"`,
			wantField: "trace_id",
		},
		{
			name:   "multiple group-by fields — not a single-field drilldown",
			query:  `env:="production" | filter trace_id:!"" | stats by (trace_id, span_id) count()`,
			wantOK: false,
		},
		{
			name:   "no existence filter — not drilldown",
			query:  `env:="production" | stats by (trace_id) count()`,
			wantOK: false,
		},
		{
			name:   "value-comparison filter — not safe for count() if",
			query:  `env:="production" | filter status:>="400" | stats by (status) count()`,
			wantOK: false,
		},
		{
			name:   "sum() not count()",
			query:  `env:="production" | filter trace_id:!"" | stats by (trace_id) sum(bytes)`,
			wantOK: false,
		},
		{
			name:   "parser stage still present — not safe",
			query:  `env:="production" | unpack_json | filter trace_id:!"" | stats by (trace_id) count()`,
			wantOK: false,
		},
		{
			name:   "no stats clause",
			query:  `env:="production" | filter trace_id:!""`,
			wantOK: false,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			base, field, ok := detectDrilldownSingleField(tc.query)
			if ok != tc.wantOK {
				t.Fatalf("detectDrilldownSingleField(%q) ok=%v want %v", tc.query, ok, tc.wantOK)
			}
			if !ok {
				return
			}
			if base != tc.wantBase {
				t.Errorf("base=%q want %q", base, tc.wantBase)
			}
			if field != tc.wantField {
				t.Errorf("field=%q want %q", field, tc.wantField)
			}
		})
	}
}

func TestDrilldownBurstCoalescer_CoalescesTwoFields(t *testing.T) {
	var callCount int
	var callMu sync.Mutex
	fireFn := func(ctx context.Context, fields []string) (map[string]fieldResult, error) {
		callMu.Lock()
		callCount++
		callMu.Unlock()
		result := make(map[string]fieldResult, len(fields))
		for _, f := range fields {
			result[f] = fieldResult{
				series: map[string]manualSeriesSamples{
					"": {Metric: map[string]string{}, Samples: nil},
				},
			}
		}
		return result, nil
	}

	c := newDrilldownBurstCoalescer(50, 30)
	key := burstKey{orgID: "default", base: `{app="foo"}`, startNs: 1000, endNs: 2000, stepNs: int64(time.Minute)}

	var wg sync.WaitGroup
	for _, f := range []string{"trace_id", "span_id"} {
		wg.Add(1)
		go func(field string) {
			defer wg.Done()
			_, err := c.Submit(context.Background(), key, field, fireFn)
			if err != nil {
				t.Errorf("Submit(%s): %v", field, err)
			}
		}(f)
	}
	wg.Wait()

	callMu.Lock()
	count := callCount
	callMu.Unlock()
	if count != 1 {
		t.Errorf("fireFn called %d times, want 1", count)
	}
}

func TestDrilldownBurstCoalescer_MaxFieldsSplitsGroups(t *testing.T) {
	callCount := 0
	var mu sync.Mutex
	fireFn := func(ctx context.Context, fields []string) (map[string]fieldResult, error) {
		mu.Lock()
		callCount++
		mu.Unlock()
		result := make(map[string]fieldResult, len(fields))
		for _, f := range fields {
			result[f] = fieldResult{series: map[string]manualSeriesSamples{"": {}}}
		}
		return result, nil
	}

	c := newDrilldownBurstCoalescer(200, 2)
	key := burstKey{orgID: "default", base: `{app="foo"}`, startNs: 1000, endNs: 2000, stepNs: int64(time.Minute)}

	var wg sync.WaitGroup
	for _, f := range []string{"f1", "f2", "f3"} {
		wg.Add(1)
		go func(field string) {
			defer wg.Done()
			c.Submit(context.Background(), key, field, fireFn) //nolint:errcheck
		}(f)
	}
	wg.Wait()

	mu.Lock()
	count := callCount
	mu.Unlock()
	if count < 2 {
		t.Errorf("fireFn called %d times with maxFields=2, 3 fields — want ≥2", count)
	}
}

func TestDrilldownBurstCoalescer_ContextCancellation(t *testing.T) {
	fireFn := func(ctx context.Context, fields []string) (map[string]fieldResult, error) {
		time.Sleep(200 * time.Millisecond)
		return map[string]fieldResult{}, nil
	}

	c := newDrilldownBurstCoalescer(100, 30)
	key := burstKey{orgID: "default", base: `{app="foo"}`, startNs: 1000, endNs: 2000, stepNs: int64(time.Minute)}

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	_, err := c.Submit(ctx, key, "trace_id", fireFn)
	if err == nil {
		t.Error("expected context cancellation error, got nil")
	}
}

func TestFusedFieldHits_MockVL(t *testing.T) {
	base := time.Unix(1700000000, 0).UTC()
	end := base.Add(5 * time.Minute)
	step := time.Minute
	ts1 := base.Add(time.Minute).Unix()
	ts2 := base.Add(2 * time.Minute).Unix()

	vlBackend := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		query := r.FormValue("query")
		if !strings.Contains(query, "count() if") {
			http.Error(w, "unexpected query: "+query, http.StatusInternalServerError)
			return
		}
		resp := fmt.Sprintf(
			`{"status":"success","data":{"resultType":"matrix","result":[`+
				`{"metric":{"__name__":"_f0"},"values":[[%d,"10"],[%d,"20"]]},`+
				`{"metric":{"__name__":"_f1"},"values":[[%d,"5"],[%d,"8"]]}]}}`,
			ts1, ts2, ts1, ts2,
		)
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprint(w, resp)
	}))
	defer vlBackend.Close()

	p := newTestProxy(t, vlBackend.URL)

	fireFn := p.fusedFieldHits("default", `{app="foo"}`, base, end, step)
	results, err := fireFn(context.Background(), []string{"trace_id", "span_id"})
	if err != nil {
		t.Fatalf("fusedFieldHits: %v", err)
	}

	r0, ok := results["trace_id"]
	if !ok || r0.err != nil {
		t.Fatalf("trace_id missing or errored: %v", r0.err)
	}
	if got := len(r0.series[""].Samples); got != 2 {
		t.Errorf("trace_id samples=%d want 2", got)
	}
	if r0.series[""].Samples[0].value != 10 {
		t.Errorf("trace_id[0].value=%v want 10", r0.series[""].Samples[0].value)
	}

	r1, ok := results["span_id"]
	if !ok || r1.err != nil {
		t.Fatalf("span_id missing or errored: %v", r1.err)
	}
	if got := len(r1.series[""].Samples); got != 2 {
		t.Errorf("span_id samples=%d want 2", got)
	}
	if r1.series[""].Samples[0].value != 5 {
		t.Errorf("span_id[0].value=%v want 5", r1.series[""].Samples[0].value)
	}
}

func TestFusedFieldHits_VLError(t *testing.T) {
	vlBackend := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "internal error", http.StatusInternalServerError)
	}))
	defer vlBackend.Close()

	p := newTestProxy(t, vlBackend.URL)
	fireFn := p.fusedFieldHits("default", `{app="foo"}`, time.Unix(1700000000, 0), time.Unix(1700000300, 0), time.Minute)
	_, err := fireFn(context.Background(), []string{"trace_id"})
	if err == nil {
		t.Fatal("expected error from VL 500, got nil")
	}
}

func TestFusedFieldHits_VLNonSuccess(t *testing.T) {
	vlBackend := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprint(w, `{"status":"error","error":"query parse error"}`)
	}))
	defer vlBackend.Close()

	p := newTestProxy(t, vlBackend.URL)
	fireFn := p.fusedFieldHits("default", `{app="foo"}`, time.Unix(1700000000, 0), time.Unix(1700000300, 0), time.Minute)
	_, err := fireFn(context.Background(), []string{"trace_id"})
	if err == nil {
		t.Fatal("expected error from non-success status, got nil")
	}
}

// TestStripDrilldownExistenceFilters_KeepsFilterPrefixForRemainingTerms: a line
// filter ANDed into the removed existence-filter stage must keep its own
// | filter prefix, or VictoriaLogs rejects the query ("unexpected token after
// [unpack_logfmt]") on every version.
func TestStripDrilldownExistenceFilters_KeepsFilterPrefixForRemainingTerms(t *testing.T) {
	cases := []struct{ in, want string }{
		{`app:="api" | filter trace_id:!"" | stats by (trace_id) count()`, `app:="api"  | stats by (trace_id) count()`},
		{`app:="api" ~"x" | unpack_logfmt | filter level:!"" ~"y"`, `app:="api" ~"x" | unpack_logfmt | filter ~"y"`},
		{`app:="api" ~"x" | format "<status>" | filter level:!"" ~"y" | stats by (level) count()`, `app:="api" ~"x" | format "<status>" | filter ~"y" | stats by (level) count()`},
		{`app:="api" | unpack_json | filter "k8s.pod.name":!"" -level:*`, `app:="api" | unpack_json | filter -level:*`},
		{`app:="api" | filter level:!""`, `app:="api" `},
	}
	for _, tc := range cases {
		if got := stripDrilldownExistenceFilters(tc.in); got != tc.want {
			t.Errorf("stripDrilldownExistenceFilters(%q)\n got: %q\nwant: %q", tc.in, got, tc.want)
		}
	}
	base, field, ok := detectDrilldownSingleFieldWithParser(`app:="api" ~"x" | unpack_logfmt | filter level:!"" ~"y" | stats by (level) count()`)
	if !ok || field != "level" || base != `app:="api" ~"x" | unpack_logfmt | filter ~"y"` {
		t.Fatalf("detectDrilldownSingleFieldWithParser: base=%q field=%q ok=%v", base, field, ok)
	}
}
